[package]
name = "bdmg"
version = "0.1.0"
authors = ["benerjo <benerjo@gmail.com>"]
edition = "2021"

[dependencies]
diesel = { version = "2.1.3", features = ["sqlite"] }
serde = "1.0"
serde_derive = "1.0"
