[package]
name = "bdmg2k"
version = "0.1.0"
authors = ["benerjo <benerjo@gmail.com>"]
edition = "2021"

[lib]
name = "bdmg2k"
path = "src/lib.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
